server {
  listen 80;
  server_name localhost;

  client_max_body_size 50M;  # 🚀 Allows uploads up to 50 MB

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  location /start {
    proxy_pass http://backend:5050;
  }

  location /stream/ {
    proxy_pass http://backend:5050;
    proxy_http_version 1.1;
    proxy_set_header Connection '';
    chunked_transfer_encoding off;
    proxy_buffering off;
    proxy_read_timeout 3600;
  }

  location /download/ {
    proxy_pass http://backend:5050;
  }


  location /validate/ {
    proxy_pass http://backend:5050;
  }
}
